version: 2
jobs:
  build:
    docker:
      - image: gridlabd/slac-master
    steps:
      - checkout            
      - run:
          name: Run the model
          command: |
            make all
      - run:
          name: Deliver results
          command: |
            mail -s "Test result" dchassin@slac.stanford.edu < my_test.csv