version: 2
jobs:
  build:
    docker:
      - image: slacgismo/circleci_gridlabd_base
    steps:
      - checkout
      - run:
          name: Run the simulation
          command: |
            gridlabd my_test.glm
      - store_artifacts:
          path: /root/project
