version: 2
jobs:
  build:
    docker:
      - image: gridlabd/slac-master
    steps:
      - checkout            
      - run:
          name: Run the simulation
          command: |
            gridlabd my_test.glm
      - run:
          name: Store results
          command: |
            mkdir -p /tmp/gridlabd
            cp my_test.csv /tmp/gridlabd
      - store_artifacts:
          path: /tmp/gridlabd
