version: 2
jobs:
  build:
    docker:
      - image: gridlabd/slac-master
    steps:
      - checkout
      - run: 
          name: Fix the image weirdness
          command: |
            yum -y install https://centos7.iuscommunity.org/ius-release.rpm
            yum -y install python36u-pip
            python3.6 -m pip install matplotlib
      - run:
          name: Run the simulation
          command: |
            gridlabd my_test.glm
      - run:
          name: Store results
          command: |
            mkdir -p /tmp/gridlabd
            tar cvfz /tmp/gridlabd/my_test.tar.gz .
            cp my_test.png /tmp/gridlabd
      - store_artifacts:
          path: /tmp/gridlabd
