version: 2
jobs:
  build:
    docker:
      - image: gridlabd/slac-master
    steps:
      - checkout
      - run:
          name: Update system
          command: |
            apt-get install software-properties-common python-software-properties --yes
            add-apt-repository -y ppa:deadsnakes/ppa
            apt update
            apt-get install python3-dev
            apt install python3.6            
            update-alternatives --install /usr/bin/python python /usr/bin/python3.6 1
            update-alternatives --set python /usr/bin/python3.6
            apt-get -y install python3-pip
            pip3 install matplotlib
      - run:
          name: Run the simulation
          command: |
            gridlabd my_test.glm
      - run:
          name: Store results
          command: |
            mkdir -p /tmp/gridlabd
            tar cvfz /tmp/gridlabd/my_test.tar.gz .
      - store_artifacts:
          path: /tmp/gridlabd
