version: 2
jobs:
  build:
    docker:
      - image: gridlabd/slac-master:dev
    steps:
      - checkout
      - run:
          name: Run the simulation
          command: |
            gridlabd my_test.glm
      - run:
          name: Store results
          command: |
            mkdir -p /tmp/gridlabd
            tar cvfz /tmp/gridlabd/my_test.tar.gz .
      - store_artifacts:
          path: /tmp/gridlabd
